<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.marda</groupId>
        <artifactId>administrative-autorization-language-courses</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>administrative-autorization-language-courses-boot</artifactId>
    <packaging>jar</packaging>
    <name>administrative-autorization-language-courses-boot</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-domain</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-application</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-configuration</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-commons</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-adapter-out-dbs-sql-postgresql</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-adapter-out-dbs-sql-mysql</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.marda</groupId>
            <artifactId>administrative-autorization-language-courses-adapter-in-rest</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <!-- Best Docker caches, fats builds, eficient upgrades -->
                <configuration>
                    <layers>
                        <enabled>true</enabled>
                    </layers>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
